#!/bin/sh
docker build -f docker/Dockerfile.front -t frontend:latest .

docker-compose -f docker/docker-compose-storages.yml stop
docker-compose -f docker/docker-compose-storages.yml rm -f
docker-compose -f docker/docker-compose-storages.yml up -d

docker-compose -f docker/docker-compose-frontend.yml stop
docker-compose -f docker/docker-compose-frontend.yml rm -f
docker-compose -f docker/docker-compose-frontend.yml up -d
