FROM python:3.6

RUN apt-get update \
 && apt-get install -y \
 && apt-get install -y libsodium-dev

WORKDIR /usr/src/app

COPY ./smbus ./
RUN pip3 install --no-cache-dir -r ./requirements.txt

CMD [ "python3", "./src/start.py" ]
