FROM gradle:6.5.1-jdk11 as builder
COPY --chown=gradle:gradle . /src
WORKDIR /src
RUN gradle assemble --no-daemon --no-build-cache

FROM openjdk:11-jre-slim as backend
ENV JAVA_OPTS="" JAVA_HEAP="-Xms1g -Xmx2g"
WORKDIR /
COPY --from=builder /src/backend/build/libs/backend-1.0.0.jar /app.jar
CMD ["sh", "-c", "java $JAVA_OPTS $JAVA_HEAP -jar app.jar"]
